# Set Swagger related Open API3 properties
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

# Set Server port
server:
  port: 8088

# Set application name
spring:
  application:
    name: cric-info-gateway
  # Set Context Path
  webflux:
    base-path: /cric-info-gateway
