#Set Swagger related Open API3 properties
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: swagger-ui-custom.html

#Set Server port
server:
  port: 8086

app:
  version: 1.0.0
  description: Application to hold Ranking related Information.

#Set Application name
spring:
  application:
    name: ranking-info-service
  #Set Context path for web-flux
  webflux:
    base-path: /ranking-service

  #Set Embedded Mongo version and features
  mongodb:
    embedded:
      version: latest
      features:
        - ONLY_WITH_SSL
        - ONLY_WINDOWS_2008_SERVER
        - ONLY_64BIT
        - NO_HTTP_INTERFACE_ARG

  #Set database name and port
  data:
    mongodb:
      database: ranking-info-service
      port: 56680
