# Set Swagger related Open API3 properties
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

# Set Context Path
spring:
  webflux:
    base-path: /player-profile
  # Set Embedded MongoDB version and features
  mongodb:
    embedded:
      version: latest
      features: ONLY_WITH_SSL, ONLY_WINDOWS_2008_SERVER, NO_HTTP_INTERFACE_ARG, ONLY_64BIT
  # Set database name and port
  data:
    mongodb:
      database: player-info-service
      port: 56607
